"""links table

Revision ID: de484c97db97
Revises: 
Create Date: 2020-08-31 12:29:38.122679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de484c97db97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_link', sa.VARCHAR(length=256), nullable=True),
    sa.Column('short_link', sa.VARCHAR(length=6), nullable=True),
    sa.Column('creation_time', sa.DATETIME(), nullable=True),
    sa.Column('visits', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_link')
    )
    # ### end Alembic commands ###
